pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'FasterHoppers'

['1.18.x', '1.19.x', '1.20.x', '1.21.x', '26.1.x'].each { v ->
	include v
	project(":${v}").projectDir = file("versions/${v}")
}