plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'com.modrinth.minotaur' version '2.+'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = "${project.archives_base_name}-${project.minecraft_version}"
}

sourceSets {
	main {
		java {
			srcDirs = [rootProject.file('src/main/java')]
		}
		resources {
			srcDirs = [
				'src/main/resources',
				rootProject.file('src/main/resources')
			]
		}
	}
}

repositories {}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
	inputs.property 'version', project.version
	filesMatching('fabric.mod.json') {
		expand 'version': inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

jar {
	inputs.property 'archivesName', project.base.archivesName
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

modrinth {
	token = System.getenv("MODRINTH_TOKEN")
	projectId = project.modrinth_project_id
	versionNumber = "${mod_version}+${minecraft_version}"
	versionType = "release"
	uploadFile = remapJar
	gameVersions = ["1.20", "1.20.1", "1.20.2", "1.20.3", "1.20.4", "1.20.5", "1.20.6"]
	loaders = ["fabric"]
	dependencies {
		required.project "fabric-api"
	}
}
